/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    // 'intro',
    // 'hello',
    // myHtmlSidebar: [
     'intro',
     'Importing an Existing Project',
     'cli',
     {
      type: 'html',
      value: '<li>',
      defaultStyle: true,
    },

      {
        type: 'html',
        value: 'CONFIGURATION', // The HTML to be rendered
        defaultStyle: true, // Use the default menu item styling
      },
      'Configuration/overview',
      {
        type: 'category', // Use 'category' type for folders
        label: 'Plugin', // Label for the folder item
        items: [
          'Configuration/Plugin/Webpack Plugin',
          'Configuration/Plugin/Vite Plugin',
          'Configuration/Plugin/Electronnegativity Plugin',
          'Configuration/Plugin/Auto Unpack Native Modules Plugin',
          'Configuration/Plugin/Local Electron Plugin',
          'Configuration/Plugin/Fuses Plugin',
          // Add other items or subfolders within Configuration/Plugin as needed
        ],
      },
      {
        type: 'category',
        label: 'Makers',
        items:[
          'Configuration/Plugin/Webpack Plugin',
        ]
      },
      {
        type: 'category',
        label: 'Publishers',
        items:[
          'Configuration/Plugin/Webpack Plugin',
        ]
      },
      'Configuration/Hooks',
      {
        type: 'html',
        value: '<li>',
        defaultStyle: true,
      },
      {
        type: 'html',
        value: 'CORE CONCEPTS', // The HTML to be rendered
        defaultStyle: true, // Use the default menu item styling
      },
      'Core Concepts/Why Electron Forge',
      'Core Concepts/Build Lifecycle',
      {
        type: 'html',
        value: '<li>',
        defaultStyle: true,
      },
      {
        type: 'html',
        value: 'BUILT-IN TEMPLATES', // The HTML to be rendered
        defaultStyle: true, // Use the default menu item styling
      },
      'Build-in Temp/Vite',
      'Build-in Temp/Vite + Typescript',
      'Build-in Temp/Webpack',
      'Build-in Temp/Webpack + Typescript',

  ],
};

export default sidebars;
